require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"

Metrics/ClassLength:
  Max: 200
  CountAsOne: ["heredoc", "array", "hash"]

Metrics/MethodLength:
  CountAsOne: ["heredoc", "array", "hash"]

Metrics/BlockLength:
  Max: 30
  CountAsOne: ["heredoc", "array", "hash"]

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
