services:
  db:
    image: postgres:16.3-alpine3.20
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    networks:
      - tincan-backend

  backend:
    build: ./backend/
    image: tincan/backend:latest
    command: /rails/bin/docker-entrypoint ./bin/rails server
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOST=db
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - "3005:3005"
    networks:
      - tincan-backend
    depends_on:
      - db

networks:
  tincan-backend:
    driver: bridge